# Generated by Django 4.0 on 2021-12-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=60)),
                ('flag', models.ImageField(blank=True, help_text='flag of country', null=True, upload_to='picture')),
                ('continet', models.CharField(max_length=50)),
            ],
        ),
    ]
